[package]
name = "vkfft-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "^0.22"
derive_more = "0.99"
vk-sys = "0.7.0"
[dependencies.vkfft-src]
path = "../vkfft-src"
version = "0.1.0"
